version: '3.5'
services:
  mongodb:
    image: mongo:latest
  py_app:
    image: py_app:latest
    ports:
      - "5000:5000"
    links:
      - mongodb:mongodb
    environment:
      - DB_HOST=mongodb
      - ACCESS_KEY=
      - SECRET=
      - REGION_NAME=
